# Generated by Django 4.2.16 on 2024-11-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2chatbot', '0003_assistant_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='file_id',
            field=models.TextField(blank=True, null=True, verbose_name='File ID'),
        ),
    ]
