# Generated by Django 4.2.16 on 2024-11-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2chatbot', '0004_alter_assistant_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='interaction_mode',
            field=models.CharField(default='tutor_asks', max_length=20),
        ),
    ]
